### ISSUE TITLE
Mobile app issues

### ISSUE THREAD

**Issue by Bazixv13** [TheRedSpy15/blazedcloud#147]
App version: 1.5.4
Android version: 13
MIUI version: Global 14.0.10
Model: M2101K7BNY

First of all I can't scroll on the transfers page idk why 
https://github.com/TheRedSpy15/blazedcloud/assets/83003002/c882ca93-a69a-45b7-8529-78e2ead82057

The second bug is that when uploading files the progress isn't shown properly it always says 100% and also the third error idk what's even that thing but at least after this error it started uploading it again

![Screenshot_2024-05-31-16-28-41-259_com.chancesoftwarellc.blazedcloud-edit.jpg](https://github.com/TheRedSpy15/blazedcloud/assets/83003002/e8123f0a-fc92-4681-9b81-96bc953cdb0f)

and the fourth error is the app size after uploading files like wtf is this it should be cleaned up after the upload is successful (clearing cache fixes it)
![Screenshot_2024-05-31-16-31-30-446_com.miui.securitycenter-edit.jpg](https://github.com/TheRedSpy15/blazedcloud/assets/83003002/bbabbff9-a4f5-446f-adc7-7562f18c10ee)

Good luck dev xoxo 💋

**Comment by TheRedSpy15** [comment]
I'll get to working on this today. The scroll issue is an easy fix

For the 100% issue, does that always happen? Or just when there was an error uploading like in the screenshot?

For that error specifically, it's hard to debug without some logs. Crashlytics for the playstore users had a couple of reports last night. One of them could be related

The cache size issue. That's caused the app making a copy of uploaded files in its internal storage. That way, it can reliably access the file until the upload is complete. But it should be cleaned after upload, and I'll have a fix for that, hopefully later today as well

**Comment by Bazixv13** [comment]
the 100 % error persists all the time even when there is no errors

**Comment by TheRedSpy15** [comment]
Just release [1.5.5](https://github.com/TheRedSpy15/blazedcloud/releases/tag/1.5.5)

Should fix at least the scroll issue, and the cache issue. Please let me know if the update still has things needing fixed

**Comment by Bazixv13** [comment]
the 100% issue is still present 
![Screenshot_2024-06-01-13-27-03-473_com.chancesoftwarellc.blazedcloud.jpg](https://github.com/TheRedSpy15/blazedcloud/assets/83003002/9006563f-291e-42d3-9fd7-8cf28b596dca)

it's always showing 100% as the progress even if it's a big file and it just started uploading
(btw it would be a nice touch if there was shown the speed of the file upload)

**Comment by TheRedSpy15** [comment]
Aha! I was able to replicate it and tracked down the cause. Fix will be available shortly!

**Comment by TheRedSpy15** [comment]
Published [1.5.6](https://github.com/TheRedSpy15/blazedcloud/releases/tag/1.5.6) with the fix
