### ISSUE TITLE
Wish: better Info

### ISSUE THREAD

**Issue by Spielmops** [TheRedSpy15/blazedcloud#53]
> Our shamelessly ChatGPT generated description

Description like any other, could be from MS. No real Info in it, but "this is the best" ....

My wish: what is it in short: cloud storage
where do the files go?
how? 
security in which way?
how much storage?
...

Spielmops

**Comment by TheRedSpy15** [comment]
Rewrote most of the readme with 25b6c7d

Can still be improve a bit further, but will do so after the holidays
